#!/usr/bin/env ruby

require 'ffi'
module LibDL
  extend FFI::Library
  ffi_lib ['./libdlinfo_wrapper.so']

	# Attach find_lib
	attach_function :find_lib, [:string], :pointer
end

path = LibDL::find_lib("libmpi.so").read_string
puts "Path seeing from Ruby: #{path}"
