#!/usr/bin/env ruby

require 'ffi'
module LibDLInfoWrapper
  extend FFI::Library

  ffi_lib FFI::Platform::LIBC
  ffi_lib ['./libdlinfo_wrapper.so']

  # Attach free()
  attach_function :free, [:pointer], :void
  # Attach find_lib_path
  attach_function :find_lib_path, [:string], :pointer
end

path_ptr = LibDLInfoWrapper::find_lib_path("libmpi.so")
exit -1 if path_ptr.null?
path = path_ptr.read_string
puts "Path seeing from Ruby: #{path}"
LibDLInfoWrapper::free(path_ptr)
